### ISSUE TITLE
Error en la Consola del navegador

### ISSUE THREAD

**Issue by Matiasqj** [gpincheiraa/angular-rut-validator#1]
Esta casi perfecto, lo trate de utilizar y todo bien, pero cuando por ejemplo en el input ingresas valores que no son acorde al rut por ejemplo "letras", manda un error en la consola del navegador

**Comment by gpincheiraa** [comment]
@Matiasqj Estimado, he subido una versión mejorada que evita que aparezca ese error.
De todas maneras aún estoy trabajando en mejorar la validación para así evitar aceptar cualquier tipo de formato inválido. Muchas gracias por el feedback.
